In [1]:
import pandas as pd

Ordinal Encoding can be done through two perfumes:-
a) Sklearn
b) Map Function

Making our own dataset

In [3]:
df = pd.DataFrame({"size" : ["s","m","l","xl","s","m","l","s","s","l","xl","m"]})
df.head(4)

  size
0    s
1    m
2    l
3   xl

In [8]:
#double bracket is used because it is a 2D data
ord_data = [["s","m","l","xl"]]  #making ordered data as we require

In [5]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
#categories can be other also that is inbuilt in ordinalEncoder categories
oe = OrdinalEncoder(categories=ord_data)  #oe = ordinal encoding
oe.fit(df[["size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [10]:
oe.transform(df[["size"]])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [3.],
       [1.]])

In [11]:
df[["en_size"]] = oe.transform(df[["size"]])

In [12]:
df

   size  en_size
0     s      0.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     s      0.0
5     m      1.0
6     l      2.0
7     s      0.0
8     s      0.0
9     l      2.0
10   xl      3.0
11    m      1.0

Now performing the same function using map function

In [17]:
#while mapping any no can be assigned
# ord_data1 = {"s":0,"m":1,"l" : 2,"xl":3}
ord_data1 = {"s":5,"m":10,"l" :20,"xl":35}

In [18]:
df["size"].map(ord_data1)

0      5
1     10
2     20
3     35
4      5
5     10
6     20
7      5
8      5
9     20
10    35
11    10
Name: size, dtype: int64

In [19]:
df["en_size_map"] = df["size"].map(ord_data1)

In [20]:
df

   size  en_size  en_size_map
0     s      0.0            5
1     m      1.0           10
2     l      2.0           20
3    xl      3.0           35
4     s      0.0            5
5     m      1.0           10
6     l      2.0           20
7     s      0.0            5
8     s      0.0            5
9     l      2.0           20
10   xl      3.0           35
11    m      1.0           10

Now we will perform ordinal encoding in big dataset

In [21]:
dataset = pd.read_csv("C:\\vs-code-folder\\ML_Practice\\Bengaluru_House_Data.csv")

In [22]:
dataset.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [27]:
dataset["area_type"].unique()

array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area'], dtype=object)

In [35]:
en_area_type = [['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area']]

In [36]:
from sklearn.preprocessing import OrdinalEncoder

In [37]:
oen = OrdinalEncoder(categories=en_area_type)  #oen = ordinal encoding
oen.fit_transform(dataset[["area_type"]])

array([[0.],
       [1.],
       [2.],
       ...,
       [2.],
       [0.],
       [0.]])

In [40]:
dataset["en_area_type"] = oen.fit_transform(dataset[["area_type"]])

In [41]:
dataset.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,en_area_type_map,en_area_type
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,NaN,0.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,NaN,1.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,NaN,2.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,NaN,0.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,NaN,0.0

In [39]:
dataset.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,en_area_type_map,en_area_type
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,NaN,0.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,NaN,1.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,NaN,2.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,NaN,0.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,NaN,0.0

In [42]:
en_area_type = {'Super built-up  Area':1, 'Plot  Area':2, 'Built-up  Area':3,
       'Carpet  Area':4}

In [43]:
dataset["area_type"].map(en_area_type)

0        1
1        2
2        3
3        1
4        1
        ..
13315    3
13316    1
13317    3
13318    1
13319    1
Name: area_type, Length: 13320, dtype: int64

In [48]:
dataset["area_type"]=dataset["area_type"].map(en_area_type)

In [49]:
dataset

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,en_area_type_map,en_area_type
0,1,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,1,0.0
1,2,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,2,1.0
2,3,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,2.0
3,1,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,1,0.0
4,1,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...
13315,3,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,3,2.0
13316,1,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,1,0.0
13317,3,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,3,2.0
13318,1,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,1,0.0
13319,1,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,0.0

thus we can convert categorical data into numerical data using map function or sk learn